/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ConexionMySql;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author MEDAC
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    ConexionMySql conexion = new ConexionMySql("aplicacionmultimedia");
    boolean bdConectada = false;
    String accionActual = "";

    public JFramePrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Escondo todos los elementos
        deshabilitarBotones(false);
        
        
        lblSeleccionarTabla.setVisible(false);
        lblSeleccionarAtributo.setVisible(false);
        lblSeleccionarCondicion.setVisible(false);

       
        lblAtributosDisponibles.setVisible(false);
        lblatts.setVisible(false);
        cmbTabla.setVisible(false);
        txtAtributos.setVisible(false);
        txtCondicion.setVisible(false);
        btnEjecutar.setVisible(false);
        
         lblAtributosDisponibles.setText("idActor, nombre, fecha_nacimiento, nacionalidad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnConectarDb = new javax.swing.JButton();
        txtAtributos = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        cmbTabla = new javax.swing.JComboBox<>();
        lblSeleccionarTabla = new javax.swing.JLabel();
        lblSeleccionarAtributo = new javax.swing.JLabel();
        lblSeleccionarCondicion = new javax.swing.JLabel();
        txtCondicion = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblatts = new javax.swing.JLabel();
        lblAtributosDisponibles = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Aplicacion Multimedia");

        btnConectarDb.setBackground(new java.awt.Color(0, 0, 0));
        btnConectarDb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConectarDb.setForeground(new java.awt.Color(255, 255, 255));
        btnConectarDb.setText("Conectar DB");
        btnConectarDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarDbActionPerformed(evt);
            }
        });

        txtAtributos.setForeground(new java.awt.Color(0, 0, 0));
        txtAtributos.setToolTipText("idPelicula, titulo, ...");

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cmbTabla.setForeground(new java.awt.Color(255, 255, 255));
        cmbTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "actor", "episodio", "genero", "lista_de_vistos", "pelicula", "pelicula_actor", "pelicula_genero", "registro_usuarios_creados", "serie", "serie_actor", "serie_genero", "temporada", "usuario" }));
        cmbTabla.setToolTipText("Seleccionar la tabla indicada para la consulta");
        cmbTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTablaActionPerformed(evt);
            }
        });

        lblSeleccionarTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeleccionarTabla.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionarTabla.setText("Seleccione Tabla: ");

        lblSeleccionarAtributo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeleccionarAtributo.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionarAtributo.setText("Seleccione atributo(s)");

        lblSeleccionarCondicion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeleccionarCondicion.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionarCondicion.setText("Seleccione condición: ");

        txtCondicion.setForeground(new java.awt.Color(0, 0, 0));
        txtCondicion.setToolTipText("where id = 1");
        txtCondicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCondicionActionPerformed(evt);
            }
        });

        btnInsertar.setBackground(new java.awt.Color(0, 0, 0));
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEjecutar.setBackground(new java.awt.Color(0, 0, 0));
        btnEjecutar.setForeground(new java.awt.Color(255, 255, 255));
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Qué desea realizar?");

        lblatts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblatts.setForeground(new java.awt.Color(0, 0, 0));
        lblatts.setText("Atributos disponibles: ");

        lblAtributosDisponibles.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblAtributosDisponibles.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeleccionarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                        .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConectarDb, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(lblatts, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(83, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSeleccionarAtributo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSeleccionarCondicion, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(cmbTabla, 0, 400, Short.MAX_VALUE)
                                    .addComponent(txtAtributos))
                                .addGap(18, 18, 18)
                                .addComponent(lblAtributosDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnConectarDb, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSeleccionarTabla)
                            .addComponent(lblatts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAtributosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(lblSeleccionarAtributo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblSeleccionarCondicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarDbActionPerformed
        try {
            if (!bdConectada) {
                conexion.conectar();
                JOptionPane.showMessageDialog(this, "Base de datos conectada correctamente", "Conexion correcta", JOptionPane.INFORMATION_MESSAGE);

                //Habilito todos los botones 
                deshabilitarBotones(true);

                //Cambio el texto del boton
                btnConectarDb.setText("Desconectar DB");
                bdConectada = true;
            } else {
                conexion.desconectar();
                bdConectada = false;
                btnConectarDb.setText("Conectar DB");

                //Deshabilito todos los botones y elementos
                deshabilitarBotones(false);
                lblSeleccionarTabla.setVisible(false);
                lblSeleccionarAtributo.setVisible(false);
                lblSeleccionarCondicion.setVisible(false);
                lblAtributosDisponibles.setVisible(false);
                lblatts.setVisible(false);
                cmbTabla.setVisible(false);
                txtAtributos.setVisible(false);
                txtCondicion.setVisible(false);
                btnEjecutar.setVisible(false);

                JOptionPane.showMessageDialog(this, "Base de datos desconectada correctamente", "Desconexion correcta", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Error en la conexion a la base de datos", "Error ocurrido", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConectarDbActionPerformed

    private void txtCondicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCondicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCondicionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        lblSeleccionarTabla.setVisible(true);
        lblSeleccionarAtributo.setVisible(true);
        lblSeleccionarCondicion.setVisible(true);
        lblAtributosDisponibles.setVisible(true);
        lblatts.setVisible(true);
        cmbTabla.setVisible(true);
        txtAtributos.setVisible(true);
        txtCondicion.setVisible(true);
        btnEjecutar.setVisible(true);

        accionActual = "buscar";

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        lblSeleccionarTabla.setVisible(true);
        lblSeleccionarAtributo.setVisible(true);
        lblSeleccionarCondicion.setVisible(false);
        lblAtributosDisponibles.setVisible(true);
        lblatts.setVisible(true);
        cmbTabla.setVisible(true);
        txtAtributos.setVisible(true);
        txtCondicion.setVisible(false);
        btnEjecutar.setVisible(true);

        accionActual = "insertar";
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        lblSeleccionarTabla.setVisible(true);
        lblSeleccionarAtributo.setVisible(true);
        lblSeleccionarCondicion.setVisible(true);
        lblAtributosDisponibles.setVisible(true);
        lblatts.setVisible(true);
        cmbTabla.setVisible(true);
        txtAtributos.setVisible(true);
        txtCondicion.setVisible(true);
        btnEjecutar.setVisible(true);

        accionActual = "actualizar";
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        lblSeleccionarTabla.setVisible(true);
        lblSeleccionarAtributo.setVisible(false);
        lblSeleccionarCondicion.setVisible(true);
        cmbTabla.setVisible(true);
        txtAtributos.setVisible(false);
        txtCondicion.setVisible(true);
        btnEjecutar.setVisible(true);

        accionActual = "borrar";
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed

        String tablaSeleccionada = cmbTabla.getSelectedItem().toString();
        String atributosSeleccionados = txtAtributos.getText();
        String condicionesSeleccionadas = txtCondicion.getText();

        try {
            switch (accionActual) {
                case "buscar":
                    conexion.ejecutarBusquedaFrame(tablaSeleccionada, atributosSeleccionados, condicionesSeleccionadas);
                    break;
                case "insertar":
                    conexion.ejecutarInsercionFrame(tablaSeleccionada, atributosSeleccionados, condicionesSeleccionadas);
                    break;
                case "actualizar":
                    conexion.ejecutarActualizacionFrame(tablaSeleccionada, atributosSeleccionados, condicionesSeleccionadas);
                    break;
                case "borrar":
                    conexion.ejecutarBorrarFrame(tablaSeleccionada, atributosSeleccionados, condicionesSeleccionadas);
                    break;
                default:
                    throw new AssertionError();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEjecutarActionPerformed

    //Segun el item del comboBox que seleccione (tabla), muestro sus atributos disponibles
    private void cmbTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTablaActionPerformed
        String tablaSeleccionada = cmbTabla.getSelectedItem().toString();

        switch (tablaSeleccionada) {
            case "actor":
                lblAtributosDisponibles.setText("idActor, nombre, fecha_nacimiento, nacionalidad");
                break;
            case "episodio":
                lblAtributosDisponibles.setText("idEpisodio, titulo, duracion, fecha_lanzamiento, idTemporada");
                break;
            case "genero":
                lblAtributosDisponibles.setText("idGenero, nombre, descripcion");
                break;
            case "lista_de_vistos":
                lblAtributosDisponibles.setText("idLista, titulo, tipo_contenido, fecha_agregado, estado, idUsuario, idPelicula, idSerie");
                break;
            case "pelicula":
                lblAtributosDisponibles.setText("idPelicula, titulo, anio_lanzamiento, duracion, url_imagen");
                break;
            case "pelicula_actor":
                lblAtributosDisponibles.setText("idPelicula, idActor");
                break;
            case "pelicula_genero":
                lblAtributosDisponibles.setText("idPelicula, idGenero");
                break;
            case "registro_usuarios_creados":
                lblAtributosDisponibles.setText("id, nombre, fecha_creacion");
                break;
            case "Actor":
                lblAtributosDisponibles.setText("idActor, nombre, fecha_nacimiento, nacionalidad");
                break;
            case "serie":
                lblAtributosDisponibles.setText("idSerie, titulo, anio_lanzamiento, num_temporadas, imagen_url");
                break;
            case "serie_actor":
                lblAtributosDisponibles.setText("idSerie, idActor");
                break;
            case "serie_genero":
                lblAtributosDisponibles.setText("idSerie, idGenero");
                break;
            case "temporada":
                lblAtributosDisponibles.setText("idTemporada, numero_temporada, numero_episodios, fecha_lanzamiento, idSerie");
                break;
            case "usuario":
                lblAtributosDisponibles.setText("idUsuario, nombre, correo, contrasena, tipo_suscripcion");
                break;
            default:
                throw new AssertionError();
        }


    }//GEN-LAST:event_cmbTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConectarDb;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JComboBox<String> cmbTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAtributosDisponibles;
    private javax.swing.JLabel lblSeleccionarAtributo;
    private javax.swing.JLabel lblSeleccionarCondicion;
    private javax.swing.JLabel lblSeleccionarTabla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblatts;
    private javax.swing.JTextField txtAtributos;
    private javax.swing.JTextField txtCondicion;
    // End of variables declaration//GEN-END:variables

    private void deshabilitarBotones(boolean habilitados) {
        btnBuscar.setEnabled(habilitados);
        btnInsertar.setEnabled(habilitados);
        btnActualizar.setEnabled(habilitados);
        btnBorrar.setEnabled(habilitados);
    }
}
