/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ConexionMySql;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author MEDAC
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    ConexionMySql conexion = new ConexionMySql("aplicacionmultimedia");
    boolean bdConectada = false;
    String accionActual = "";
    
    public JFramePrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        btnBuscar.setEnabled(false);
        btnInsertar.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnBorrar.setEnabled(false);
        
        lblSeleccionarTabla.setVisible(false);
        lblSeleccionarAtributo.setVisible(false);
        lblSeleccionarCondicion.setVisible(false);
        cmbTabla.setVisible(false);
        txtAtributos.setVisible(false);
        txtCondicion.setVisible(false);
        btnEjecutar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnConectarDb = new javax.swing.JButton();
        txtAtributos = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        cmbTabla = new javax.swing.JComboBox<>();
        lblSeleccionarTabla = new javax.swing.JLabel();
        lblSeleccionarAtributo = new javax.swing.JLabel();
        lblSeleccionarCondicion = new javax.swing.JLabel();
        txtCondicion = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Aplicacion Multimedia");

        btnConectarDb.setBackground(new java.awt.Color(0, 0, 0));
        btnConectarDb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConectarDb.setForeground(new java.awt.Color(255, 255, 255));
        btnConectarDb.setText("Conectar DB");
        btnConectarDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarDbActionPerformed(evt);
            }
        });

        txtAtributos.setForeground(new java.awt.Color(0, 0, 0));
        txtAtributos.setToolTipText("idPelicula, titulo, ...");

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cmbTabla.setForeground(new java.awt.Color(255, 255, 255));
        cmbTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "actor", "episodio", "genero", "lista_de_vistos", "pelicula", "pelicula_actor", "pelicula_genero", "registro_usuarios_creados", "serie", "serie_actor", "serie_genero", "temporada", "usuario" }));
        cmbTabla.setToolTipText("Seleccionar la tabla indicada para la consulta");

        lblSeleccionarTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeleccionarTabla.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionarTabla.setText("Seleccione Tabla: ");

        lblSeleccionarAtributo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeleccionarAtributo.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionarAtributo.setText("Seleccione atributo(s)");

        lblSeleccionarCondicion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeleccionarCondicion.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionarCondicion.setText("Seleccione condición: ");

        txtCondicion.setForeground(new java.awt.Color(0, 0, 0));
        txtCondicion.setToolTipText("where id = 1");
        txtCondicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCondicionActionPerformed(evt);
            }
        });

        btnInsertar.setBackground(new java.awt.Color(0, 0, 0));
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEjecutar.setBackground(new java.awt.Color(0, 0, 0));
        btnEjecutar.setForeground(new java.awt.Color(255, 255, 255));
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Qué desea realizar?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeleccionarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                        .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(83, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConectarDb, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSeleccionarAtributo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSeleccionarCondicion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                                .addComponent(cmbTabla, 0, 400, Short.MAX_VALUE)
                                .addComponent(txtAtributos))
                            .addComponent(txtCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnConectarDb, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lblSeleccionarTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblSeleccionarAtributo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblSeleccionarCondicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarDbActionPerformed
        try {
            if(!bdConectada){
                conexion.conectar();
                JOptionPane.showMessageDialog(this, "Base de datos conectada correctamente", "Conexion correcta", JOptionPane.INFORMATION_MESSAGE);

                //Habilito todos los botones 
                btnBuscar.setEnabled(true);
                btnInsertar.setEnabled(true);
                btnActualizar.setEnabled(true);
                btnBorrar.setEnabled(true);
                
                //Cambio el texto del boton
                btnConectarDb.setText("Desconectar DB");
                bdConectada = true;
            }else{
                conexion.desconectar();
                bdConectada = false;
                btnConectarDb.setText("Conectar DB");
                
                //Deshabilito todos los botones y elementos
                btnBuscar.setEnabled(false);
                btnInsertar.setEnabled(false);
                btnActualizar.setEnabled(false);
                btnBorrar.setEnabled(false);
                lblSeleccionarTabla.setVisible(false);
                lblSeleccionarAtributo.setVisible(false);
                lblSeleccionarCondicion.setVisible(false);
                cmbTabla.setVisible(false);
                txtAtributos.setVisible(false);
                txtCondicion.setVisible(false);
                btnEjecutar.setVisible(false);
                
                JOptionPane.showMessageDialog(this, "Base de datos desconectada correctamente", "Desconexion correcta", JOptionPane.INFORMATION_MESSAGE);
            }
           
            
        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Error en la conexion a la base de datos", "Error ocurrido", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnConectarDbActionPerformed

    private void txtCondicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCondicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCondicionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        lblSeleccionarTabla.setVisible(true);
        lblSeleccionarAtributo.setVisible(true);
        lblSeleccionarCondicion.setVisible(true);
        cmbTabla.setVisible(true); 
        txtAtributos.setVisible(true);
        txtCondicion.setVisible(true);
        btnEjecutar.setVisible(true);
        
        accionActual = "buscar";
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        lblSeleccionarTabla.setVisible(true);
        lblSeleccionarAtributo.setVisible(true);
        lblSeleccionarCondicion.setVisible(false);
        cmbTabla.setVisible(true); 
        txtAtributos.setVisible(true);
        txtCondicion.setVisible(false);
        btnEjecutar.setVisible(true);
        
        accionActual = "insertar";
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        lblSeleccionarTabla.setVisible(true);
        lblSeleccionarAtributo.setVisible(true);
        lblSeleccionarCondicion.setVisible(true);
        cmbTabla.setVisible(true); 
        txtAtributos.setVisible(true);
        txtCondicion.setVisible(true);
        btnEjecutar.setVisible(true);
        
        accionActual = "actualizar";
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        lblSeleccionarTabla.setVisible(true);
        lblSeleccionarAtributo.setVisible(false);
        lblSeleccionarCondicion.setVisible(true);
        cmbTabla.setVisible(true); 
        txtAtributos.setVisible(false);
        txtCondicion.setVisible(true);
        btnEjecutar.setVisible(true);
        
         accionActual = "borrar";
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        
        String tablaSeleccionada = cmbTabla.getSelectedItem().toString();
        String atributosSeleccionados = txtAtributos.getText();
        String condicionesSeleccionadas = txtCondicion.getText();
         try {
            switch (accionActual) {
                case "buscar":
                    String [] atributosSeparados = atributosSeleccionados.split(",");
                    
                    ResultSet rs = conexion.ejecutarSelect("SELECT " + atributosSeleccionados + " FROM " + tablaSeleccionada + " " + condicionesSeleccionadas);
                    
                    JFrameSelect jFrameSelect = new JFrameSelect(rs);
                    jFrameSelect.setVisible(true);
                    
                    
                    
                    while(rs.next()){
                        System.out.print("- ");
                        for (int i = 0; i < atributosSeparados.length; i++) {

                           //Borro los espacios entre cada atributo
                           String atributo = atributosSeparados[i].trim();
                           System.out.print(atributo + ": " + rs.getString(atributo) + " | ");
                        }
                       System.out.println("");
                    }
                    break;

                case "insertar":

                        int filasInsertadas = conexion.ejecutarInsertDeleteUpdate("INSERT INTO " + tablaSeleccionada + " VALUES (" + atributosSeleccionados + ")");

                        if(filasInsertadas > 0){
                            JOptionPane.showMessageDialog(this, "El registro fue insertado correctamente", "Insercion", JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(this, "El registro no fue insertado", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    break;
                case "actualizar":
                        int filasActualizadas = conexion.ejecutarInsertDeleteUpdate("UPDATE  " + tablaSeleccionada + " SET " + atributosSeleccionados + " " + condicionesSeleccionadas);

                        if(filasActualizadas > 0){
                            JOptionPane.showMessageDialog(this, "El registro fue actualizado correctamente", "Insercion", JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(this, "El registro no fue actualizado", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    break;
                case "borrar":
                    int filasBorradas = conexion.ejecutarInsertDeleteUpdate("DELETE FROM " + tablaSeleccionada + "  " + condicionesSeleccionadas);

                        if(filasBorradas > 0){
                            JOptionPane.showMessageDialog(this, "Borrado correctamente", "Insercion", JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(this, "El registro no fue borrado correctamente", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    break;
                default:
                    throw new AssertionError();
                }

            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEjecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConectarDb;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JComboBox<String> cmbTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSeleccionarAtributo;
    private javax.swing.JLabel lblSeleccionarCondicion;
    private javax.swing.JLabel lblSeleccionarTabla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAtributos;
    private javax.swing.JTextField txtCondicion;
    // End of variables declaration//GEN-END:variables
}
